version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customshop-db

  app:
    build: .
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - db

  app_clone:
    build: .
    restart: always
    ports:
      - 8086:8080
    depends_on:
      - db