SET NAMES utf8mb4;

CREATE TABLE PRODUCT_CATEGORIES
(
    PRODUCT_CATEGORY_ID VARCHAR(36) UNIQUE,
    PARENT_PRODUCT_CATEGORY_ID VARCHAR(36),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,
    PRIMARY KEY (PRODUCT_CATEGORY_ID)
);

CREATE TABLE PRODUCT_CATEGORY_DETAILS
(
    PRODUCT_CATEGORY_DETAIL_ID VARCHAR(36) UNIQUE,
    PRODUCT_CATEGORY_ID VARCHAR(36),

    DETAIL_TYPE VARCHAR(256),
    DETAIL_TEXT VARCHAR(8192),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,
    CONSTRAINT `FK_DESCRIBED_PRODUCT_CATEGORY`
        FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES (PRODUCT_CATEGORY_ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    PRIMARY KEY (PRODUCT_CATEGORY_DETAIL_ID)
);

CREATE TABLE PRODUCTS
(
    PRODUCT_ID VARCHAR(36) UNIQUE,
    PRODUCT_CATEGORY_ID VARCHAR(36),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,

    CONSTRAINT `FK_RELATED_PRODUCT_CATEGORY`
        FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES (PRODUCT_CATEGORY_ID)
        ON DELETE CASCADE
        ON UPDATE RESTRICT,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRODUCT_DETAILS
(
    PRODUCT_DETAIL_ID VARCHAR(36) UNIQUE,
    PRODUCT_ID VARCHAR(36),
    DETAIL_TYPE VARCHAR(256),
    DETAIL_TEXT VARCHAR(8192),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,

    CONSTRAINT `FK_DESCRIBED_PRODUCT`
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    PRIMARY KEY (PRODUCT_DETAIL_ID)
);

CREATE TABLE PRODUCT_INSTANCES
(
    PRODUCT_INSTANCE_ID VARCHAR(36) UNIQUE,
    PRODUCT_ID VARCHAR(36),
    PRODUCT_INSTANCE_COUNT decimal(19,2),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,

    CONSTRAINT `FK_RELATED_PRODUCT`
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    PRIMARY KEY (PRODUCT_INSTANCE_ID)
);

CREATE TABLE PRODUCT_INSTANCE_DETAILS
(
    PRODUCT_INSTANCE_DETAIL_ID VARCHAR(36) UNIQUE,
    PRODUCT_INSTANCE_ID VARCHAR(36),
    DETAIL_TYPE VARCHAR(256),
    DETAIL_TEXT VARCHAR(8192),

    AUDITABLE_STATUS VARCHAR(8),
    AUD_STATUS_UPDATE_REASON VARCHAR(36),
    CREATE_JWT_TOKEN VARCHAR(256),
    UPDATE_JWT_TOKEN VARCHAR(256),
    CREATE_DATE_TIME_UTC TIMESTAMP,
    UPDATE_DATE_TIME_UTC TIMESTAMP,

    CONSTRAINT `FK_DESCRIBED_PRODUCT_INSTANCE`
        FOREIGN KEY (PRODUCT_INSTANCE_ID) REFERENCES PRODUCT_INSTANCES (PRODUCT_INSTANCE_ID)
            ON DELETE CASCADE
            ON UPDATE RESTRICT,
    PRIMARY KEY (PRODUCT_INSTANCE_DETAIL_ID)
);


